version: '3'

services:
  mongodb:
    image: mongo
    networks:
      - todo-network
    volumes:
      - todo_mongo:/todo-mongo

  frontend:
    build: ./todo-list-front/
    hostname: todo-front
    volumes:
      - todo_front:/app/dist/front

  backend:
    build: ./todo-list-back/
    hostname: todo-back
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    networks:
      - todo-network
    volumes:
      - todo_front:/app/public/front:ro

networks:
  todo-network: {}

volumes:
  todo_front:
  todo_mongo:
